### ISSUE TITLE
Open specific route always in modal

### ISSUE THREAD

**Issue by nextlevelshit** [lsirivong/gatsby-plugin-modal-routing#29]
Is it possible to open a specific route always in a modal. When typing the route in my browser's adressbar directly it will open as a ordinary page. This is not always wanted. Some modals like image galleries should always open in a separate modal, don't you think?

**Comment by lsirivong** [comment]
Hi @nextlevelshit!

I think what you're saying makes sense, but I wonder if that could be achieved more appropriately in your own app code. If you know you always want to render a modal at a certain URL, you could use `react-modal` or even own modal code to manage that.

The primary use case for this plugin is to render modals when navigated via browser, but render a static non-modal version of the page when navigated directly - rather than forcing them as you suggest.

I'm happy to reconsider if other folks have ideas on how this could be beneficial and what the API for it would look like though!
