### ISSUE TITLE
Is there a way to navigate to next/prev modals as in the gatsbygram example?

### ISSUE THREAD

**Issue by ilia-luk** [lsirivong/gatsby-plugin-modal-routing#43]
Firstly, let me say that this plugin works great, I found it after following a few hacky tutorials which tried to implement something similar without any success, and now I can't be happier from the result.

The thing is, I've checked out the second example you referenced:

[https://gatsbygram-with-gatsby-plugin-modal-routing.netlify.com/](https://gatsbygram-with-gatsby-plugin-modal-routing.netlify.com/)

and I've noticed there are navigation links between modals, I tried to find instructions on this but without success, I checked out the repository, looked around and strangely it doesn't use the plugin, which makes me wonder why do you use it as an example?

so my questions are:
- is there any elegant way to currently do it with this plugin and it's just undocumented?
- if not, do you plan on supporting this kind of functionality?, I mean, would I be able to navigate to another modal from within the modal while passing the `closeTo` and stating that it should remain as a modal of the original page?

**Comment by lsirivong** [comment]
Yes!

The correct source for the gatsbygram example is here: https://github.com/lsirivong/gatsbygram-with-gatsby-plugin-modal-routing

Here's how it's navigating previous / next: https://github.com/lsirivong/gatsbygram-with-gatsby-plugin-modal-routing/blob/master/src/components/modal.js#L72

I'll update the gatsbygram example so that it links to the correct source!

You can also see in [the other example](https://gatsby-starter-with-gatsby-plugin-modal-routing.netlify.com/) that when you open a model link while already in a modal, it will load in the existing modal, so you don't necessarily have to do it with `navigate` like in the gatsbygram example: https://github.com/lsirivong/gatsby-starter-with-gatsby-plugin-modal-routing/blob/master/src/pages/page-2.js#L15
