### ISSUE TITLE
Provide an example for using custom CSS classes

### ISSUE THREAD

**Issue by ryanblakely** [lsirivong/gatsby-plugin-modal-routing#44]
It would be helpful to provide an example showing how to pass an object to the modal that would provide a custom CSS class. I'm looking to customize the modal and am having trouble finding information on how to do this.

Currently I have:

`gatsby-config.js`:

```
    {
      resolve: `gatsby-plugin-modal-routing`,
      options: {
        // A selector to set react-modal's app root to, default is `#___gatsby`
        // See http://reactcommunity.org/react-modal/accessibility/#app-element
        appElement: '#___gatsby',

        // Object of props that will be passed to the react-modal container
        // See http://reactcommunity.org/react-modal/#usage
        modalProps: {
          className: "myContentClass",
        },
      }
```

But the className is not applied to the React Modal. Am I going about this correctly?

**Comment by lsirivong** [comment]
Hmm, I believe that should work. The only thing I can think of is make sure to restart your gatsby dev server after editing `gatsby-config.js`. You should also be able to reference the react-modal docs on styling for usage: http://reactcommunity.org/react-modal/styles/

I won't be able to look closer right now, but hopefully that gets you unstuck! I'll work on getting this documented better, since this and transition styling has come up a few times now.

**Comment by ryanblakely** [comment]
Thanks for your quick reply. I solved my issue. The problem was that I had 

```
    `gatsby-plugin-modal-routing`,
    {
      resolve: `gatsby-plugin-modal-routing`,
      options: {
        // A selector to set react-modal's app root to, default is `#___gatsby`
        // See http://reactcommunity.org/react-modal/accessibility/#app-element
        appElement: '#___gatsby',

        // Object of props that will be passed to the react-modal container
        // See http://reactcommunity.org/react-modal/#usage
        modalProps: {
          className: "myContentClass",
        },
      }
```

Once I removed the first `gatsby-plugin-modal-routing`, I was able to use custom styling as expected. Great work on the plugin!
